### ISSUE TITLE
Using LocalAuthEnabled inside Caddy configuraiton

### ISSUE THREAD

**Issue by trajche** [greenpau/caddy-auth-saml#1]
Thanks for the awesome work greenpau. I see that in UI you have a variable LocalAuthEnabled, any way similar functionality can be used in the Caddy conf files? 

Trying to get this working for a use case I have:
I'd like to allow access to the reverse proxy target only if the user has been authenticated via SAML.

**Comment by greenpau** [comment]
> Thanks for the awesome work greenpau.

@trajche , I think documentation is by and large complete :-) The core functionallity works, but I am still working to make it ready. Planning to finish up in then next two days. Once I tag `v1.0.0`, it means it is working.

> I see that in UI you have a variable LocalAuthEnabled

This is hidden functionality. It triggers a simple login menu with the ability to pass a value. I did not finish that implementation, simply reserved a space for it.

>  I'd like to allow access to the reverse proxy target only if the user has been authenticated via SAML.

That is one of my use cases too. The way you implement it would be using `caddy-auth-jwt` plugin, which I am working on right now too. Here is how it works.

Provided the configuration in https://github.com/greenpau/caddy-auth-saml/blob/master/assets/conf/Caddyfile.json, you want to protect `/health` endpoint. Currently, the is no authorization there.

```json
            {
              "handle": [
                {
                  "body": "OK",
                  "handler": "static_response",
                  "status_code": 200
                }
              ],
              "match": [
                {
                  "path": [
                    "/health"
                  ]
                }
              ],
              "terminal": true
            },
```

You would modify it like this:

```json
            {
              "handle": [
                {
                  "handler": "authentication",
                  "providers": {
                    "jwt": {
                      "token_name": "JWT_TOKEN",
                      "token_secret": "383aca9a-1c39-4d7a-b4d8-67ba4718dd3f",
                      "token_issuer": "7a50e023-2c6e-4a5e-913e-23ecd0e2b940",
                      "auth_url_path": "/saml",
                      "allow_roles": [
                        "AzureAD_Viewer",
                        "AzureAD_Editor",
                        "AzureAD_Administrator"
                      ]
                    }
                  }
                },
                {
                  "body": "OK",
                  "handler": "static_response",
                  "status_code": 200
                }
              ],
              "match": [
                {
                  "path": [
                    "/health"
                  ]
                }
              ],
              "terminal": true
            },
```

If a user authenticated with SAML, then the endpoint would issue JWT token to the user.
The `caddy-auth-jwt` would validate the token and redirect the user to IdP, e.g. Azure AD.

Is that what you were looking for?

**Comment by trajche** [comment]
Got it. So `"auth_url_path": "/saml"` is where the redirect would happen if the user is missing a jet token. I haven't had a chance to look at caddy-auth-jwt. I will give this a try and come back to you :)

Also, I've been using Apache+Shibboleth / Nginx+Shibboleth (what a pain!) so I will open up some more features/issues that I have on my mind right now, based on previous experience. Hope I can contribute with some code in the future too. Thanks for opening the "role not mandatory" one 👍

**Comment by greenpau** [comment]
> Got it. So "auth_url_path": "/saml" is where the redirect would happen if the user is missing a jwt token. I haven't had a chance to look at caddy-auth-jwt. I will give this a try and come back to you :)

@trajche, exactly! I did not publish `caddy-auth-jwt` yet. It would take a few days.

**Comment by greenpau** [comment]
>  It would take a few days.

@trajche , at the moment I am learning how to build the plugins :-) I hope I understand it, at least conceptually.

**Comment by trajche** [comment]
> > It would take a few days.
> 
> @trajche , at the moment I am learning how to build the plugins :-) I hope I understand it, at least conceptually.

@greenpau I'm starting to have a closer look as well! :)

I assume `caddy-auth-jwt` is related to the discussion here: https://github.com/BTBurke/caddy-jwt/issues/57

Will be waiting patiently to test!

**Comment by greenpau** [comment]
> I assume caddy-auth-jwt is related to the discussion here: BTBurke/caddy-jwt#57

@trajche , yes! :smile:

**Comment by greenpau** [comment]
> Got it. So "auth_url_path": "/saml" is where the redirect would happen if the user is missing a jwt token. I haven't had a chance to look at caddy-auth-jwt. I will give this a try and come back to you :)

@trajche, currently, the automated redirect is all done. The are a number of options:

1. Redirect URL parameter: `https://app:3443/saml?redirect_url=/alertmanager`.
2. Configuration option under `ui`:

```json
                      "ui": {
                        "auto_redirect_url": "/alertmanager"
```

The role attribute is not mandatory. Rather, if a user does not have a role. The user gets `anonymous` role. JWT plugin would need to be configured to trust that role. That is still in works. But, I, by and large, finished saml plugin.

**Comment by trajche** [comment]
@greenpau Thanks for your work on this. I compiled caddy together with your latest caddy-saml version. When adding and endpoint behind the JWT authorization I keep getting 401. For this example, I added the following:

```
{
                  "handle": [
                    {
                      "handler": "authentication",
                      "providers": {
                        "jwt": {
                          "token_name": "JWT_TOKEN",
                          "token_secret": "383aca9a-1c39-4d7a-b4d8-67ba4718dd3f",
                          "token_issuer": "7a50e023-2c6e-4a5e-913e-23ecd0e2b940",
                          "auth_url_path": "/saml"
                        }
                      }
                    },
                    {
                      "body": "OK",
                      "handler": "static_response",
                      "status_code": 200
                    }
                  ],
                  "match": [
                    {
                      "path": [
                        "/health"
                      ]
                    }
                  ],
                  "terminal": true
                },
```

as suggested but every time I visit /health endpoint I get 401 no matter if I've previously done the /saml authentication or if I am visiting from a new session (incognito). Any tips on how to proceed here?

**Comment by greenpau** [comment]
@trajche , jwt plugin isn’t complete yet. I am almost done! 😄 will release EOD today NY time. Will post here.

**Comment by trajche** [comment]
@greenpau Just saw v0.0.7 released. Let me know if this is something that can be worked with? Thanks!

**Comment by greenpau** [comment]
@trajche , not yet, got stuck on some issue, but will be out of the weeds soon. As soon as it is ready, I will post here.

**Comment by greenpau** [comment]
@trajche , currently, there are two issues left:
1. cache cleanup routine... needs to be implemented
2. token validator ... I tried to make it work tonight, but failed ... need to do some more debugging.
it is a home stretch right now.

**Comment by trajche** [comment]
thanks @greenpau for keeping me in the loop. I guess the token validator needs to be functioning properly before I can go ahead and test this?

**Comment by greenpau** [comment]
> thanks @greenpau for keeping me in the loop. I guess the token validator needs to be functioning properly before I can go ahead and test this?

@trajche , I released JWT plugin :smile: Closing this issue. Please try:

```bash
xcaddy build v2.0.0 --output saml-jwt-caddy \
                --with github.com/greenpau/caddy-auth-saml@v1.1.10  \
                --with github.com/greenpau/caddy-auth-jwt@v0.0.13
```

If you run into issue, please open a new issue in https://github.com/greenpau/caddy-auth-jwt
