### ISSUE TITLE
automatically redirect to saml IDP if there is only one alternative

### ISSUE THREAD

**Issue by trajche** [greenpau/caddy-auth-saml#3]
My assumption is the UI and buttons that are added on the screen shown at /saml is for the purpose of having the option of multiple SAML providers. 

In many of the cases I've worked on, organizations only use one of these: Azure, Ubisecure, Auth0 or another SAML IDP.  It would be ideal if there is an option to automatically redirect users to the IDP of choice (if there is only one provider).

**Comment by greenpau** [comment]
> My assumption is the UI and buttons that are added on the screen shown at /saml is for the purpose of having the option of multiple SAML providers.

@trajche , yes, UI buttons are there for multi IdP support. 

I will be adding the handling of `/saml?sso=true` and the ability to specify automatic redirect redirect.

**Comment by greenpau** [comment]
@trajche , importantly, you could have multiple endpoints for SAML, each pointing to a separate instance of the plugin.

For example, `/saml/azure1` will autoredirect to IdP Tenant 1, while `/saml/azure2 will auto-redirect to IdP Tenant2.

```

... SAML config for Provider 1 ...

              "match": [
                {
                  "path": [
                    "/saml/azure1*"
                  ]
                }
              ],

...

... SAML config for Provider 2 ...

              "match": [
                {
                  "path": [
                    "/saml/azure2*"
                  ]
                }
              ],


```

**Comment by greenpau** [comment]
@trajche , this is now complete. Please see https://github.com/greenpau/caddy-auth-saml#miscellaneous.

just change `auto_redirect` to `true`. As long as there is a single provider, it would allow the redirect.

https://github.com/greenpau/caddy-auth-saml/blob/master/assets/conf/Caddyfile.json#L20-L25
