### ISSUE TITLE
make providing of certificate file voluntary, get it from metadata.xml instead

### ISSUE THREAD

**Issue by trajche** [greenpau/caddy-auth-saml#4]
The metadata.xml, especially in the case of Azure IDP already contains the certificate that you are requesting as .pem file and so do a lot of other IDPs. It's found in the `<X509Certificate>` tag. Ideally one would just upload the metadata XML.

Note: Azure also provides a remote URL for getting this metadata that can be downloaded, however not all IDPs do this, so perhaps a remote file download option is not the best idea.

**Comment by greenpau** [comment]
> Note: Azure also provides a remote URL for getting this metadata that can be downloaded, however not all IDPs do this, so perhaps a remote file download option is not the best idea.

@trajche . yes, I mentioned the URL there https://github.com/greenpau/caddy-auth-saml/blob/master/README.md#azure-ad-idp-metadata-and-certificate. In fact, you can pass the URL via `idp_metadata_location`. It does not have to be local.

**Comment by greenpau** [comment]
@trajche , the `idp_metadata_location` has the logic parsing local or remote url.

**Comment by greenpau** [comment]
@trajche , I was also thinking of passing the cert via environment variable. This way there is no need to store local files.

**Comment by trajche** [comment]
@greenpau I meant for the `idp_sign_cert_location`. The IDP certificate itself is found inside the metadata.xml, therefore you wouldn't need to provide it via env var and in the case of Azure SAML you wouldn't even need to have an option `idp_sign_cert_location` since everything you need is in `idp_metadata_location` payload.

**Comment by greenpau** [comment]
@trajche , the functionality provided by this plugin moved to [caddy-auth-portal](https://github.com/greenpau/caddy-auth-portal). Caddyfile support exists. Please migrate. If you have an issue, please open one in https://github.com/greenpau/caddy-auth-portal/issues.

Please re-open this specific issue in https://github.com/greenpau/caddy-auth-portal/issues.
