### ISSUE TITLE
use the singleSignOn URL rather than the application URL redirect

### ISSUE THREAD

**Issue by trajche** [greenpau/caddy-auth-saml#5]
The SAML standard has a defined sign-on service. If you use this instead of the Microsoft Application URL it will skip at least one redirect when getting back the SAML signature. This SingleSignOn URL is found in the metadata.xml `<SingleSignOnService>`.

I will try to test & implement this and get back to you here...

**Comment by greenpau** [comment]
> I will try to test & implement this and get back to you here...

@trajche , awesome! :+1:

**Comment by greenpau** [comment]
> This SingleSignOn URL is found in the metadata.xml <SingleSignOnService>.

@trajche . it may for other SAML IdP, but not for Azure. The metadata reference is generic endpoint.

https://github.com/greenpau/caddy-auth-saml/blob/665d28325f65057e7a7e07d598153cd90e70fdd1/assets/idp/azure_ad_app_metadata.xml#L153-L154

**Comment by trajche** [comment]
Hmm, I do believe the above URLs are tenant specific which means it will validate against the organization. I did a test by changing the az.LoginURL with my tenant specific SingleSignOnService:
![image](https://user-images.githubusercontent.com/2382019/82764986-bf5bee00-9e1b-11ea-9733-6ecf8c0123e2.png)

which means in the above link you pasted, 1b9e886b-8ff2-4378-b6c8-6771259a5f51 is actually your organization's tenant ID so all responses would be validated against it. One tenant = one IDP in Azure.

This doesn't need to be application-specific since what matters is the SAML request (which contains the return URL).  It seems to do a proper redirect and Microsoft recognizes it, but it's not formatted properly with the SAML request:
![image](https://user-images.githubusercontent.com/2382019/82765023-f6320400-9e1b-11ea-8d7a-3d0c372a3cbe.png)

I believe the SAML sso library you use from crewjam actually has the example exactly like this with a generic SAML IDP test.

p.s. That's how we made this SAML plugin for a Kanban board generic so it works with any SAML IDP (including Azure). ref: https://github.com/trajche/SamlAuth

**Comment by greenpau** [comment]
> 1b9e886b-8ff2-4378-b6c8-6771259a5f51

@trajche , that is the Tenant ID. The ID is unique to each tenant. 

```
  "tenant_id": "1b9e886b-8ff2-4378-b6c8-6771259a5f51",
  "application_id": "623cae7c-e6b2-43c5-853c-2059c9b2cb58",
```

The login URL is a mix of tenant id, application id, and application name.

**Comment by trajche** [comment]
@greenpau Yes, that's what I said above as well.

My suggestion above is that you might not need the application ID at all. You can use the single sign-on URL from the metadata which you mentioned above:
https://github.com/greenpau/caddy-auth-saml/blob/665d28325f65057e7a7e07d598153cd90e70fdd1/assets/idp/azure_ad_app_metadata.xml#L153-L154
to actually send a SAML request to it. I am new to Golang but I will try to build a little demo with crewjam and then I could get your help to implement in this plugin for a 'generic' SAML plugin rather than Azure Application dependent one.

**Comment by trajche** [comment]
Adding some more info. We've done an Nginx + Shibboleth / SAML implementation in a similar manner where the user is redirected to the IDP using the HTTP Redirect binding (SAML standard). It's basically an encoded SAML Request in a parameter:

```
<samlp:AuthnRequest AssertionConsumerServiceURL="https://rp.xxxx.dev/service1"
    Destination="https://login.microsoftonline.com/xxxx-xxxx-xxxx-xxxx-xxxx/saml2"
    ID="ONELOGIN_cb63e0231fe2aa24a2bd0xxxxxxxxx" IssueInstant="2020-05-24T22:50:06Z"
    ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Version="2.0"
    xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
    xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol">
    <saml:Issuer>https://rp.xxxx.dev/service1</saml:Issuer>
    <samlp:NameIDPolicy AllowCreate="true"
        Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified"/>
    <samlp:RequestedAuthnContext Comparison="exact">      <saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport</saml:AuthnContextClassRef>
    </samlp:RequestedAuthnContext>
</samlp:AuthnRequest>
```

plus an additional Relay State parameter, which instructs where to redirect the user after authentication:
```
&RelayState=%2Fservice1
```

As you see in the above it's a SP initiated SAML authentication without the need to specify an application, the only things that are important is the AssertionConsumerServiceURL.

Will try to provide a bit more specific information once I check out the crewjam SAML library.

**Comment by greenpau** [comment]
> &RelayState=%2Fservice1

@trajche , I actually didn't think about it 😄Thank you for the pointer! :-)

Btw, if you are using Azure to authenticate to AD, you might like this one https://github.com/greenpau/go-get-aws-keys

**Comment by greenpau** [comment]
> Also what this does, is that it skips that Azure application javascript-y redirect in between. Perhaps it might also fix the Microsoft Edge bug.

@trajche , previously opened https://github.com/greenpau/caddy-auth-saml/issues/7 for it. The issue is how Edge handles cookies. Did not have time to look into it.
